spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mybatisplusdemo?userSSL=false&serverTimezone=UTC
    username: root
    password: 123456
  mvc:
    servlet:
#      项目地址
      path: /springboot-mvc01
#      静态资源路径的配置
    static-path-pattern: /templates/**
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
#    map-underscore-to-camel-case: true
# 静态资源配置
